# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &Orgnew
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgnewMSP

        # ID to load the MSP definition as
        ID: OrgnewMSP

        MSPDir: crypto-config/peerOrganizations/orgnew.gtbcsf.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgnewMSP.admin', 'OrgnewMSP.peer', 'OrgnewMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgnewMSP.admin', 'OrgnewMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OrgnewMSP.admin')"

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.orgnew.gtbcsf.com
              Port: 7051
